
[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4" }

[lib]
name = "authentication_manager"
path = "./src/authentication_manager.rs"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-beta.8", features = ["api-all"] }
walkdir = "2.3.2"
cpal = "0.13.4"
rodio = "0.14.0"
json = "0.12.4"
tokio = { version = "1.13.0", features = ["full"] }
tokio-tungstenite = "0.16.0"
log = "0.4.14"
tungstenite = "0.16.0"
futures-util = "0.3.18"
tauri-plugin-websocket = { path = "/home/m1cl/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-plugin-websocket" }
config = "0.11.0"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
oauth2 = "4.1.0"
url = "2.2.2"
rusqlite = "0.26.3"
rocket = "0.5.0-rc.1"
dirs = "4.0.0"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
